import React, { useState, useEffect } from 'react';
import { useApp } from '../../context/AppContext';
import { X, AlertTriangle, ArrowRight, Save } from 'lucide-react';

export default function ContextOverflowModal() {
  const { overflowData, handleRespondToOverflow, settings } = useApp();
  const [editedText, setEditedText] = useState('');

  useEffect(() => {
    if (overflowData && overflowData.text) {
      setEditedText(overflowData.text);
    }
  }, [overflowData]);

  if (!overflowData) return null;

  const stepName = overflowData.profileName || 'AI Profile';
  const sizeKb = overflowData.sizeBytes ? Math.ceil(overflowData.sizeBytes / 1024) : 'unknown';

  return (
    <div className={`fixed inset-0 z-50 flex items-center justify-center titlebar-nodrag select-none p-8 ${(settings?.interface?.blur ?? true) ? 'bg-black/60 backdrop-blur-sm' : 'bg-[#011419]'}`}>
      <div className="w-full max-w-3xl h-full max-h-[600px] bg-[#011419] border border-orange-950 rounded-xl shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-800/80 bg-[#0a161d] shrink-0 text-orange-400">
          <div className="flex items-center space-x-2">
            <AlertTriangle className="w-5 h-5 animate-pulse" />
            <h3 className="text-white font-bold text-base">Output Context Overflow Warning</h3>
          </div>
          <span className="text-[10px] bg-orange-500/10 text-orange-400 border border-orange-500/20 font-bold px-2 py-0.5 rounded uppercase">
            Size: {sizeKb} KB
          </span>
        </div>

        {/* Instructions */}
        <div className="p-6 pb-2 shrink-0 space-y-1">
          <p className="text-sm text-gray-200 font-bold">
            The output generated by "{stepName}" is excessively large.
          </p>
          <p className="text-xs text-gray-400 leading-normal">
            This could affect performance or get rejected by subsequent API context windows. You can edit the text below to trim down parts, or send the original content anyway.
          </p>
        </div>

        {/* Text Editor Area */}
        <div className="flex-1 p-6 pt-2 overflow-hidden flex flex-col">
          <textarea 
            value={editedText}
            onChange={(e) => setEditedText(e.target.value)}
            className="flex-1 w-full bg-[#051116] border border-gray-800 hover:border-gray-700 focus:border-accent text-gray-200 text-xs font-mono rounded-lg p-4 focus:outline-none resize-none custom-scrollbar"
            placeholder="Edit context payload here..."
          />
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-end p-4 border-t border-gray-800/80 bg-[#0a161d] space-x-3 shrink-0">
          <button 
            onClick={() => handleRespondToOverflow('send_anyway', overflowData.text)}
            className="px-4 py-2 bg-[#011419] hover:bg-[#1a2d32] border border-gray-800 text-gray-300 rounded-lg text-xs font-semibold transition-colors cursor-pointer flex items-center space-x-1.5"
          >
            <ArrowRight className="w-3.5 h-3.5" />
            <span>Send Anyway</span>
          </button>
          
          <button 
            onClick={() => handleRespondToOverflow('send_edited', editedText)}
            className="px-4 py-2 bg-accent hover:brightness-110 text-[#011419] rounded-lg text-xs font-bold transition-all cursor-pointer flex items-center space-x-1.5"
          >
            <Save className="w-3.5 h-3.5" />
            <span>Send Edited Content</span>
          </button>
        </div>

      </div>
    </div>
  );
}
